-- Execute this in the Supabase SQL Editor
CREATE TABLE sensor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature INT NOT NULL,
    smoke_level INT NOT NULL,
    system_status VARCHAR(50) NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
